services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./faiss_index:/app/faiss_index
      - ./data.json:/app/data.json
      - ./access.txt:/app/access.txt
    env_file:
      - .env
    restart: always